server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    charset utf-8;

    gzip on;
    gzip_types text/html text/css application/javascript;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Force download for .exe files
    location ~* \.exe$ {
        add_header Content-Disposition 'attachment';
        add_header Cache-Control 'no-cache, no-store, must-revalidate';
        add_header X-Content-Type-Options 'nosniff';
    }
}
