server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    charset utf-8;

    gzip on;
    gzip_types text/html text/css application/javascript;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    # Force download for .exe files
    location ~* \.exe$ {
        add_header Content-Disposition 'attachment; filename="LupaApp.exe"';
        add_header Cache-Control 'no-cache, no-store, must-revalidate';
        add_header X-Content-Type-Options 'nosniff';
        types { application/octet-stream exe; }
        default_type application/octet-stream;
    }
}
